spec:
  replicas: 1
  strategy:
    type: Rolling
  template:
    spec:
      containers:
      - image: myproject/customer-service-sc
        name: customer-service-sc
        ports:
        - containerPort: 8000
          protocol: TCP
