server:
  port: 8000
  servlet:
    contextPath: "/api/v1"

spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#service:
#  message: "Hello"